<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CapOffloadProbe.Producer-bb9ae2d8-3e97-4228-af58-8a4fe71f449c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetCore.CAP" Version="10.0.1" />
    <PackageReference Include="DotNetCore.CAP.Kafka" Version="10.0.1" />
    <PackageReference Include="DotNetCore.CAP.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CapOffloadProbe.Shared\CapOffloadProbe.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.Local.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
